### ISSUE TITLE
Add instruction output to color version

### ISSUE THREAD

**Issue by christiansiegel** [christiansiegel/knitter#7]
color version: https://github.com/christiansiegel/knitter/tree/feat/color

todo: save instruction files

**Comment by christiansiegel** [comment]
Added `instruction.txt` for now.

@alfred11111: Please let me know if that works for you :wink:

**Comment by mrnann** [comment]
Wow. You are fast.
Im working on the coloured version and also the square one.
I ll let you know once I completed any of them.
They should be all work.
Now i have to put all the nails on the canvas first then start threading.

**Comment by mrnann** [comment]
For the coloured version, there are now 3 colours you made for the code.
Is it possible to add more color to make it more realistic ?
I tried generated some image but not quite close to the original image, because there are some color missing.
This link below have someone made coloured thread art. Those works seems have lots colours thread.
https://escapekit.ca/post/186892829836/thread-portraits-moscow-based-programmer-ani/embed

**Comment by christiansiegel** [comment]
Hmm..I already assumed that it wouldn't work well. I think creating a proper colored version like the one of Ani Abakumova requires a different algorithm.

Well, it was worth a try. Thanks for trying out.
I don't think I'll make another version though.
